### PR TITLE
Upgrade tensorflow to 2.1.0

### LINKED ISSUE #2: Update Tensorflow
Currently we use 1.15 which is quite old.

It also has a packaging bug which prevents us from specifying it as a dependency with Python Poetry: 

https://github.com/python-poetry/poetry/issues/1330

https://github.com/tensorflow/tensorflow/pull/32758

Fixed in https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0-rc2

### PR DESCRIPTION
**Pull request by dyeo**
## 🎉 Issues resolved:

- closes #2 

## 🧪 How to Test

1. Update your CUDA install to v10.1 and install the latest cuDNN for that version
2. Restart your computer
3. Update your installation and dependencies by running `pip install .`
4. Run the game as normal

## Caveats

- ~~Upgrading to tensorflow 2.1.0 results in [this issue](https://github.com/tensorflow/tensorflow/issues/22794) on windows 10 devices, even with the correct CUDA version installed. The suggested fix is to downgrade to tensorflow 14.0.0, which obviously doesn't benefit us.~~
  - This seems to be a non-issue.

### CODE REVIEW

**Review by dustinlacewell — COMMENTED** [review]
I don't really have enough ML background to review the semantics of these changes, but the Python looks fine. Let's wait for a review by @WAUthethird to get it merged.

**Review by WAUthethird — COMMENTED** [review]
Well done! Seems this upgrade addresses all the issues and conversion factors needed, however I'm unsure about requiring users to install CUDA. Seems that Microsoft Visual C++ Redistributable for Visual Studio 2015 needs to be installed to solve the error, as per this link: https://github.com/tensorflow/tensorflow/issues/22794#issuecomment-573297027

Will test and report back.

**Comment by WAUthethird** [comment]
I've tested on TF 2.1 (most recent version) and TF 2.0 and I don't receive CUDA errors, rather the expected warnings in the initialization process. I have the Visual C++ Rd for VS 2015 installed. CUDA is not required.

You can safely update the package versions. I've confirmed that tensorflow 2.1.0 and tensorflow-estimator 2.0.1 work with this PR with modification to the version checks. tensorboard can most likely be updated without issue.

**Comment by dyeo** [comment]
Updated to 2.1.0 🚀

**Pull request merged**
